from User import User
persona1=User("Carola","Guerrero")
persona2=User("Antonio","Ribeiro")
persona3=User("Trenza","la RIO")

print(" Persona 1 ")
persona1.depositar(30)
persona1.depositar(300)
persona1.depositar(3000)
persona1.girar(2000)
print(persona1.__dict__)
persona1.balance_usuario()

print(" Persona 2 ")
persona2.depositar(300)
persona2.depositar(2000)
persona2.girar(200)
persona2.girar(500)
print(persona1.__dict__)
persona2.balance_usuario()

print(" Persona 3 ")
persona3.depositar(1000)
persona3.girar(200)
persona3.girar(100)
persona3.girar(300)
print(persona3.__dict__)
persona3.balance_usuario()
print( "transferir dinero persona 2 a persona 3")
persona2.transferir_dinero(persona3, 600)
